# SPDX-License-Identifier: Apache-2.0

services:
  dev:
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - .:/workspace
      - /var/run/docker.sock:/var/run/docker.sock
    working_dir: /workspace
    command: bash
    stdin_open: true
    tty: true
    environment:
      - TERM=xterm-256color
      - DOCKER_BUILD=1

  test:
    build:
      context: .
      dockerfile: Dockerfile.test
    volumes:
      - .:/test
    working_dir: /test
    command: ./tests/scripts/run-all-tests.sh
    environment:
      - DOCKER_CONTAINER=1
      - RANDOM_TESTS=${RANDOM_TESTS:-0}
    
  benchmark:
    build:
      context: .
      dockerfile: Dockerfile.test
    volumes:
      - .:/test
    working_dir: /test
    command: ./benchmark.sh
    
  ubuntu:
    build:
      context: .
      dockerfile: Dockerfile.ubuntu
    volumes:
      - .:/test
    working_dir: /test
    environment:
      - DOCKER_BUILD=1
      - DOCKER_CONTAINER=1