# SPDX-License-Identifier: Apache-2.0
name: CI

on:
  push:
    branches: [ main, develop ]
    tags:
      - 'v*'
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
      
    - name: Set up build environment
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential git
        
    - name: Build and Test
      run: |
        # Use Docker for all builds and tests
        docker compose build
        docker compose run --rm -T test
        
    - name: Run benchmarks
      run: |
        docker compose run --rm benchmark
        
    - name: Extract binary from Docker
      run: |
        # Build and extract the binary
        docker compose run --rm dev sh -c "DOCKER_BUILD=1 make clean all"
        
    - name: Upload binary
      uses: actions/upload-artifact@v4
      with:
        name: gitmind-linux
        path: gitmind

  cross-platform:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
        
    runs-on: ${{ matrix.os }}
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Install dependencies (macOS)
      if: runner.os == 'macOS'
      run: |
        brew install openssl
        
    - name: Build
      run: |
        DOCKER_BUILD=1 make clean
        DOCKER_BUILD=1 make
        
    - name: Test
      run: |
        export PATH="$PWD:$PATH"
        ./tests/integration/test.sh